#! /bin/sh
### BEGIN INIT INFO
# Provides:          ganglia-monitor-workload
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/gmond-workload
NAME=ganglia-monitor-workload
DESC="Ganglia Monitor Daemon for workload"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet \
		--exec $DAEMON -- --pid-file /var/run/$NAME.pid --conf=/etc/ganglia/gmond_workload.conf
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        start-stop-daemon --stop  --quiet --oknodo -p /var/run/$NAME.pid \
                2>&1 > /dev/null
	echo "$NAME."
	;;
  reload)
  ;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

